package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("Dirty little test #2")
    void generatedTest() {
        step("Open https://rt.pornhub.com", () -> {
            // todo
        });

        step("Check if sexual wellness exist", () -> {
            // todo
        });
    }

    @Test
    @Description("Autogenerated, because your test steps contain text 'http...' and the page has &lt;title&gt;")
    @DisplayName("Page title test")
    void titleTest() {
        step("Open url 'https://rt.pornhub.com'", () ->
            open("https://rt.pornhub.com"));

        step("Checking that the page title has is 'Порно Видео Онлайн Бесплатно - Русское Porno, Порно Фильмы, XXX - Порнхаб'", () -> {
            String expectedTitle = "Порно Видео Онлайн Бесплатно - Русское Porno, Порно Фильмы, XXX - Порнхаб";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }
}